from pathlib import Path
import sys,json
R=Path('/mnt/f/LaTeX/BVE research');O=Path('/mnt/f/tools/math-audit-round5-20260921');Art='research/artifacts/proof-audit-round5-20260921/lean';Exec=Art+'/independent-replay'
sys.path.insert(0,str(R/'_xsoc1_work/plugins/manage-math-research-program/skills/manage-math-research-program/scripts'))
import research_review as V
Readback=json.loads((O/'readback-review-dispatch.json').read_text())['bundle'];assert V.verify_review_bundle(R,Readback)['verdict']=='APPROVED'
First=json.loads((O/'semantic-review-dispatch.json').read_text())['bundle'];assert V.verify_review_bundle(R,First)['verdict']=='INCOMPLETE'
assert (R/Exec/'REPORT.json').is_file()
Inputs=[{'path':'lean-proof/SL/AuditRound5.lean','role':'current-formal-source'},{'path':'docs/SL_cofinite_left_definite.tex','role':'analytic-context-and-formal-boundaries'},{'path':Readback+'/report.json','role':'blind-readback'},{'path':First+'/report.json','role':'preserved-incomplete-prior-review'}]
Names=['CONTRACT.md','positive-contract.json','false-expected-contract.json','final/declarations.json','final/public-theorem-axioms.json','final/formal-statements.txt','final/formal-statements-fully-explicit.txt','final/local-definition-closure.txt','final/loaded-modules.json','final/module-artifact-hashes.json','environment.json','root-object-bindings.json','closure-consistency.json','coordinator-replay/RESULT.json','coordinator-replay/final/formal-statements.txt','coordinator-replay/final/formal-statements-fully-explicit.txt','coordinator-replay/final/local-definition-closure.txt','coordinator-replay/root-AuditRound5.olean.bin']
for N in Names:Inputs.append({'path':Art+'/'+N,'role':'formal-target-or-reference-execution-identity'})
# Include all new independent results and actual transcripts, without duplicating the copied old-input folder.
for P in sorted((R/Exec).rglob('*')):
 if not P.is_file():continue
 Rel=P.relative_to(R/Exec)
 if 'frozen' in Rel.parts:continue
 Inputs.append({'path':str(P.relative_to(R)),'role':'independent-native-replay-evidence'})
Claims=[
 {'id':'R5-Lean-semantic-v2','verification':'formal','statement':'Independently compare all59 actual elaborated definitions/theorem declarations with the contract, unchanged source, actual blind readback and analytic context. Check real carrier versus complex analysis, true polynomial derivative/evaluation/residues, m>=2 restrictions and natural subtraction, arbitrary cutoffs of algebraic spans, proper-inclusion witness1+X, positive L versus positive even L assumptions, real2x2 matrix inverse, exact endpoint correction preserving divisibility, explicit kernel inclusion in the trace-lift statement, and a nonvacuous eight-conjunct root. Prior semantic approval is provenance, not a substitute for your checking. No Sobolev/Green/cofinite analytic closure or full project formalization is asserted.'},
 {'id':'R5-independent-execution-and-scope','verification':'software','statement':'Audit the newly supplied ACTUAL independent native execution: match the complete spawn/scope-steering/completion transcripts, fork_context=false, verifier identity distinct from authors, explicit hash-bounded runtime read/execute permission, source snapshot identity, own fresh output root and object bindings, executed exact-contract/export/positive/negative-control logs, all59 type/definition/axiom/dependency comparisons, and actual before/after runtime/import byte rehashes. Verify the first INCOMPLETE gap (no independent checker ran Lean) is remedied by this separate stateless verifier personally compiling and inspecting its own root, not by relabeling coordinator/author logs. Check all supplied transcript and evidence hashes and any reported comparison adjustments. The direct negative is a strict-inclusion/equality type mismatch and positive controls compile the witness/inequality; do not describe it as proving False. This obligation audits the recorded independent native execution under COORDINATOR_ATTESTED_TOOL_TRANSCRIPT and its precise limits. It does NOT claim a self-contained offline distribution of the operating system/compiler/Mathlib, cryptographic service attestation, another compiler run by this receipt-auditor, or a maintained-verifier implementation replay by the independent executor. The old maintained-verifier outcomes remain scoped historical records. Do not access an external runtime yourself under this snapshot-only review; inspect the actual fresh executor record instead. If the independent run, isolation, exact target or hash evidence is missing, leave the relevant obligation INCOMPLETE. No current mathematical source was changed to obtain acceptance.'}
]
Packet=V.create_packet(R,{'kind':'mathematics','author_ids':['01a06f46-dd03-7c83-9267-32048412c359','01a0c22b-dabe-7f30-a5bd-08b48dae6ae3','01a0c22b-f107-7520-9d75-33258752765c'],'inputs':Inputs,'claims':Claims})
(O/'semantic-v2-review-packet.json').write_text(json.dumps(Packet,ensure_ascii=False,indent=2)+'\n');print(Packet['packet_sha256'])
