from pathlib import Path
import sys,json
Root=Path('/mnt/f/LaTeX/BVE research');Out=Path('/mnt/f/tools/math-audit-round5-20260921');Art='research/artifacts/proof-audit-round5-20260921/lean'
sys.path.insert(0,str(Root/'_xsoc1_work/plugins/manage-math-research-program/skills/manage-math-research-program/scripts'))
import research_review as R
Readback=json.loads((Out/'readback-review-dispatch.json').read_text())['bundle'];assert R.verify_review_bundle(Root,Readback)['verdict']=='APPROVED'
assert json.loads((Root/Art/'coordinator-replay/RESULT.json').read_text())['status']=='PASS'
Inputs=[{'path':'lean-proof/SL/AuditRound5.lean','role':'current-formal-source'},{'path':'docs/SL_cofinite_left_definite.tex','role':'intended-analytic-context-with-explicit-formal-scope-limits'},{'path':Readback+'/report.json','role':'independent-blind-readback'}]
Names=['CONTRACT.md','FINAL_CHECKS.json','positive-contract.json','false-expected-contract.json','environment.json','snapshot-binding.json','root-object-bindings.json','author-verifier-binding.json','author-verifier-binding-checked.json','closure-consistency.json','controls-result.json','command-index.json','protection-check.json','InspectAuditRound5.lean','run_lean.py','final/AuditRound5.lean','final/declarations.json','final/public-theorem-axioms.json','final/formal-statements.txt','final/formal-statements-fully-explicit.txt','final/local-definition-closure.txt','final/loaded-modules.json','final/module-artifact-hashes.json','controls/PositiveControls.lean','controls/FalseHighSpanEquality.lean','verifier-positive/run-manifest.json','verifier-false-expected/run-manifest.json','source-snapshot/01-cofinite_replacement_proof.md','source-snapshot/02-candidate_proof.md','coordinator-replay/RESULT.json','coordinator-replay/replay_lean.py','coordinator-replay/InspectAuditRound5.lean','coordinator-replay/ContractCheck.lean','coordinator-replay/PositiveControls.lean','coordinator-replay/FalseHighSpanEquality.lean','coordinator-replay/root-AuditRound5.olean.bin','coordinator-replay/artifact-rehash.json','coordinator-replay/final/declarations.json','coordinator-replay/final/loaded-modules.json']
for Sub in ['logs','coordinator-replay/logs','pins']:
 Names += [str(P.relative_to(Root/Art)) for P in (Root/Art/Sub).rglob('*') if P.is_file()]
for Name in sorted(set(Names)):
 assert (Root/Art/Name).is_file(),Name
 Inputs.append({'path':Art+'/'+Name,'role':'formal-contract-export-environment-or-actual-execution'})
Claims=[
 {'id':'R5-Lean-semantic','verification':'formal','statement':'Independently compare all59 elaborated declarations and the actual blind readback with the author contract and intended polynomial formulas. Verify the carrier Polynomial R, actual derivative/evaluation and boundary residues, natural subtractions and domain m>=2, all-index high spans, oblique 1+X witness, actual2x2 matrix columns/determinant/two-sided inverse, positive even L versus bare-positive algebraic conditions, endpoint correction and divisibility, trace-lift splitting and explicitly assumed kernel inclusion. The root must be a meaningful conjunction of these conclusions, not an assumed proposition. Detect any mismatch, hidden narrowing or vacuous premise. Complex Sobolev closure, cutoff approximation, Green integration, leading-term tail equality and all-cofinite analytic classification are expressly NOT formalized; do not upgrade them from this file.'},
 {'id':'R5-Lean-execution','verification':'software','statement':'Audit actual Windows-PE Lean4.31.0 execution through WSL, pinned environment and imports, exact root type and all59 transitive axiom closures. Check the fresh coordinator root, unchanged source and inspection/control input-object hashes, exported declaration/definition byte equality, one expected local module path change, actual module/runtime rehash and positive/false-equality controls. A negative control rejects a false equality by type mismatch; its explicit negation and1+X witness compile in the positive control, so do not misreport it as a failed proof of False. Check the maintained verifier positive exact target and negative expected-contract mismatch retain semantic.status=not_reviewed; distinguish author checks, coordinator replay and this independent semantic verdict. Preserve failed author elaborations and the disclosed union-of-declarations/root-only dependency comparison adjustment. No full Lake build or native Linux runtime is claimed. Report any machine evidence not reproducible from the frozen packet instead of assuming it was executed.'}
]
Packet=R.create_packet(Root,{'kind':'mathematics','author_ids':['01a06f46-dd03-7c83-9267-32048412c359','01a0c22b-dabe-7f30-a5bd-08b48dae6ae3','01a0c22b-f107-7520-9d75-33258752765c'],'inputs':Inputs,'claims':Claims})
(Out/'semantic-review-packet.json').write_text(json.dumps(Packet,ensure_ascii=False,indent=2)+'\n');print(Packet['packet_sha256'])
