from pathlib import Path
import json
O=Path('/mnt/f/tools/math-audit-round8-20260922');R=Path('/mnt/f/LaTeX/BVE research');A=R/'research/artifacts/proof-audit-round8-20260922'
Authors=['01a06f46-dd03-7c83-9267-32048412c359','01a0c4c7-52f9-71e3-bc0b-ef3e30abb78e','01a0c4c7-595b-7a40-9740-ec99ceb721a6','01a0c4cc-45bc-77e1-8ce3-f79b2f3d31aa']
def item(n,role): return {'path':str((A/n).relative_to(R)),'role':role}
def save(n,d): (O/(n+'-spec.json')).write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
save('certificate-review',{'kind':'mathematics','author_ids':Authors,'inputs':[item('certificate-evidence.zip','frozen author source and raw execution archive'),item('certificate/certificate.py','exact interval implementation'),item('certificate/README.md','mathematical contract and scope'),item('certificate/verification.json','author evidence inventory not independent approval'),item('certificate/results.json','author exact outputs'),item('submitted/checks.py','external audit regressions'),item('submitted/analytic_repairs.md','proposed analytic repairs to check')], 'claims':[
{'id':'certificate-soundness','verification':'exact-computation','statement':'Independently audit Fraction-only interval arithmetic, Machin/Taylor error bounds, every domain/division guard, root sign and endpoint image direction, interval expression for T3, Cz and 0.8256 ratio. Verify the reported enclosures follow, and that Decimal outward display is not reused as unproved input. Audit the continuous B(t)<=9 argument in README (all t in (pi/2,pi)); finite samples alone do not prove it. The full sliver domain and T1 are explicitly excluded from this certificate.'},
{'id':'certificate-execution','verification':'software','statement':'Perform fresh independent executions from copies of the frozen inputs. Authorized output directory only: /mnt/f/tools/math-audit-round8-20260922/certificate-reviewer. You may extract the supplied frozen zip there and execute its copied certificate and supplied checks with local Python; the source project remains read-only. Read OS Python/runtime files only as needed to execute. Do not seek memory, skills, authors or other project files. Run ordinary and -O, and fresh -S certificate positives/negative controls where supported. Check original 22 supplied checks, all 19 certificate groups, all14 declared negative controls and appropriate own edge cases. Save raw argv/exit/stdout/stderr/source-hash receipts and a manifest under this output directory; reject any counterexample rather than editing reviewed source. Do not claim process import isolation merely from stdlib source imports. No absolute full-machine isolation is asserted.'},
{'id':'certificate-provenance','verification':'software','statement':'Verify the frozen zip manifest, original input identities and raw failed/successful execution receipts. Distinguish author evidence, your actual fresh executions, legacy platform-specific libm counterexamples and unproved spectral/continuous statements. Preserve failures. Report exact checked scopes and any actionable remaining defect.'}]})
d=json.loads((A/'formal-blind/declarations.json').read_text())
save('formal-readback',{'kind':'formal-readback','author_ids':Authors,'inputs':[item('formal-blind/declarations.json','formal-statement')],'claims':[{'id':p['declaration'],'declaration':p['declaration']} for p in d['public_declarations']]})
print('Prepared certificate-review and formal-readback specs')
