from pathlib import Path
import json,shutil,sys
R=Path('/mnt/f/LaTeX/BVE research');O=Path('/mnt/f/tools/math-audit-round9-20260923');A=R/'research/artifacts/proof-audit-round9-20260923';P=Path(json.loads((O/'formal-review-root.json').read_text())['project'])
sys.path.insert(0,'/mnt/c/Users/HuangZY/.codex/plugins/cache/math-research/manage-math-research-program/2.0.1/skills/manage-math-research-program/scripts')
import research_review as V
B=json.loads((O/'formal-isolated-readback-received.json').read_text())
if B['verdict']!='APPROVED':raise RuntimeError('Independent formal readback unavailable')
Copy=[(A/'lean-author/raw-evidence.zip','author-raw-evidence.zip'),(A/'lean-author/archive-manifest.json','author-archive-manifest.json'),(A/'lean-author/HUMAN-CONTRACT.md','HUMAN-CONTRACT.md'),(A/'lean-author/author-result.json','author-result.json'),(A/'lean-author/REPORT.md','author-report.md'),(A/'lean-author/positive-contract.json','positive-contract.json'),(A/'analytic-repair.md','analytic-repair.md'),(R/'docs/SL_fixed_n_supremum.tex','SL_fixed_n_supremum.tex')]
for S,N in Copy:
	D=P/'inputs'/N
	if D.exists() and D.read_bytes()!=S.read_bytes():raise RuntimeError('Input drift '+N)
	shutil.copyfile(S,D)
Inputs=[dict(path='inputs/'+N,role='actual-formal-definition-or-intended-local-contract') for N in ['AuditRound9.lean','declarations.json','environment.json','lean-toolchain']+[N for _,N in Copy]]
Inputs += [dict(path=B['bundle']+'/'+N,role='actual-independent-blind-readback') for N in ['report.json','receipt.json','dispatch.json','spawn.json','completion.json']]
Claims=[
	dict(id='R9-fresh-Lean-execution',verification='formal',statement='Personally execute a fresh compiler replay from the frozen author archive in a NEW private directory /mnt/f/tools/math-audit-round9-20260923/formal-reviewer. Inspect its author_runner.py, replay.py and launch_replay.py before running copied launch_replay.py with a never-used prefix. The supplied runner may read only the existing pinned Windows Lean4.31.0 executable, installed plugin verification/runtime code, original lean-proof/lake-manifest.json and declared Mathlib/package build artifacts needed for compilation. Reading those runtime dependencies is authorized; unrelated source, memory, skills or author conversations are not. No global configuration changes, downloads, Lake rebuild or reuse of an author root olean as your own new compilation. Check every actual argv/exit/stdout/stderr, fresh root artifact, exact 15-conjunct type, definitions and transitive axioms; use actual checks of every bound imported artifact and runtime identity before/after. Independently reproduce one positive exact target and the missing-target, wrong-sign expected type and extra-unproved-premise controls, with their specific mismatch causes. A missing run or a generic nonzero exit is not success. Preserve any failures and exact limits. Save evidence and identify all output paths in final JSON.'),
	dict(id='R9-Lean-semantic-fidelity',verification='formal',statement='Compare the supplied independent blind readback and your freshly elaborated declarations against the explicit human contract and actual analytic source. Account for all binders of all 59 exported declarations (25 source theorems, 13 definitions/abbreviations and generated auxiliaries). Check finite Fin n real integral-normal projection including zero norm and idempotence, the arbitrary real-module linear-functional correction with nonzero normalization and preservation of a kernel equation, actual 2x2 matrix entries and arbitrary-n powers/J-conjugation, physical similarity transport, omega=y/(s*t), nonzero-domain hypotheses, real sin/cos reflection and positive interior factor/zero iff. No root conclusion may be hidden in an unproved premise, no redefinition of the mathematical target is acceptable. The extra-premise negative control is a genuine type mismatch, not a proof of its arbitrary H.'),
	dict(id='R9-Lean-exact-scope',verification='formal',statement='Check that root closure is genuinely closed under only propext, Classical.choice and Quot.sound, with no sorryAx/new axioms/unsafe/unknown dependency, and that dependency/definition exports describe the compiled object. Distinguish algebraic interfaces from analytic block-integral identification, weighted projection (not selected), eigenfunction differentiability, infinite spectral expansion/reduced inverse/Green concentration, ODE derivation, 2n root counting, candidate limit and global extrema, none of which this Lean source fully proves. Inspect retained initial compile/positive failure and interrupted negative-premise attempt without upgrading them to passes; the completed replacement run is separate. A full project Lake build is not requested or claimed. Report execution and semantic conclusions separately, including any remaining formalization gaps.')]
Spec=dict(kind='mathematics',author_ids=['01a06f46-dd03-7c83-9267-32048412c359','01a0cbe7-a5ba-7be1-9170-4484e929436b',B['reviewer_id']],inputs=Inputs,claims=Claims)
for N,D in [('formal-isolated-semantic-spec.json',Spec),('formal-isolated-semantic-packet.json',V.create_packet(P,Spec))]:(O/N).write_text(json.dumps(D,ensure_ascii=False,indent=2)+'\n')
print('Prepared formal semantic and real execution packet',len(Inputs),'inputs',flush=True)
