from pathlib import Path
import json,sys
R=Path('/mnt/f/LaTeX/BVE research');O=Path('/mnt/f/tools/math-audit-round9-20260923');A='research/artifacts/proof-audit-round9-20260923'
sys.path.insert(0,'/mnt/c/Users/HuangZY/.codex/plugins/cache/math-research/manage-math-research-program/2.0.1/skills/manage-math-research-program/scripts')
import research_review as V
Names=['scripts/_gapn2_second_variation_probe.py','scripts/_gapn2_symmetry_recon.py','scripts/_gapn2_jacobian_probe.py','scripts/_gapn2_jacobian_analytic.py','scripts/op03_gap_table.json',A+'/software-integration.json',A+'/software-reproduction.md',A+'/before/scripts/_gapn2_second_variation_probe.py',A+'/analytic-repair.md',A+'/submitted/analytic_repairs.md']
Files=['_gapn2_second_variation_probe.py','REPORT.md','DELIVERY.json','input_manifest.json','execution_manifest.json','test_candidate.py','tests.json','tests_optimized.json','regression_projection.py','old_projection_red.log','new_projection_green_final.log','sensitivity.py','sensitivity.json','sensitivity.log','R1_compatibility.json']
for Case in ['n2R4SUP','n3R4SUP','n2R10SUP','n2R4INF']:
	Files += [Case+'.json',Case+'.log']
Names += [A+'/software-author/'+N for N in Files]
Spec=dict(kind='mathematics',author_ids=['01a06f46-dd03-7c83-9267-32048412c359','01a0cbe7-3a93-7ec3-94d5-1481aa88a92d'],inputs=[dict(path=N,role='frozen-program-data-and-numerical-evidence') for N in Names],claims=[
	dict(id='R9-software-projection',verification='software',statement='Independently inspect and execute the current repaired block projection. Check Euclidean and width-weighted metrics, exact zero-normal handling, extreme scaling and invalid finite/dimension/width inputs. Reproduce the actual historical AST projection failure on unequal widths, the supplied exact SL counterexample, and the real n2R4 source-case first variation. Verify tangency is checked with separate direct integration, not merely the constructed dot product.'),
	dict(id='R9-software-integration',verification='software',statement='Independently execute meaningful checks of true block endpoint integration, weighted normalization, unweighted spectral pairings and the second-variation sum. Re-run normal/-O regressions and the four required CLI cases, checking candidate/dependency hashes against supplied snapshots. Test the no-clamping finite-difference positivity guard, retained CLI defaults and R=1 behavior. Runtime missing evidence is INCOMPLETE, not approval. Work in a fresh private copied input tree, never author/current live source outside the packet.'),
	dict(id='R9-software-scope',verification='numerical',statement='Check actual cutoff, quadrature and FD sensitivity and honest remaining numerical errors, including the small INF direction and double-precision cancellation. Inspect P2b changes separately from the block-average bug. Check P3 fixed-width direction breakpoints and half-interface acceleration sign/factor, without inferring an eta limit or universal Hessian identity. Verify report counts/residuals/signs match actual data, tests reject bad controls under -O, and no sampled sign is called a proof of definiteness or box-constrained optimality.')])
(O/'software-review-spec.json').write_text(json.dumps(Spec,ensure_ascii=False,indent=2)+'\n');P=V.create_packet(R,Spec);(O/'software-review-packet.json').write_text(json.dumps(P,ensure_ascii=False,indent=2)+'\n');print('Prepared software packet',len(Names),'inputs',flush=True)
