from pathlib import Path
import json,shutil,sys,hashlib
R=Path('/mnt/f/LaTeX/BVE research');O=Path('/mnt/f/tools/math-audit-round9-20260923');A=R/'research/artifacts/proof-audit-round9-20260923';P=A/'software-review2'
sys.path.insert(0,'/mnt/c/Users/HuangZY/.codex/plugins/cache/math-research/manage-math-research-program/2.0.1/skills/manage-math-research-program/scripts')
import research_review as V
P.mkdir();D=P/'inputs/candidate';D.mkdir(parents=True)
for F in (O/'software-f1-author').iterdir():
	if F.is_file():shutil.copyfile(F,D/F.name)
for N in ['test_candidate.py','sensitivity.py','regression_projection.py']:shutil.copyfile(O/'software-author'/N,D/N)
(P/'AGENTS.md').write_text('# Round9 software acceptance after F1\n\nOnly frozen candidate, independent reviewer artifacts and actual native receipts belong here. A separate library lock avoids interrupting the parent correction releases. Preserve first rejection and all candidate bytes. User requested continued round9 repair; coordinator must later match the accepted candidate against the actual installed script before publication.\n')
for Src,Name in [(A/'software-review1/execution-evidence.zip','first-review-execution.zip'),(A/'software-review1/manifest.json','first-review-manifest.json'),(O/'software-review-completion.json','first-review-native-completion.json'),(A/'analytic-repair.md','analytic-repair.md')]:shutil.copyfile(Src,P/'inputs'/Name)
(P/'inputs/repair-scope.md').write_text('''# Candidate repair and independent execution scope

The first independent review found that positive bump half-widths 1e-20 and 1e-16 could collapse or lose substantial mass in double coordinates. This candidate adds checked_bump_breaks: at least 2**20 coordinate spacings per half-width, radius-error rejection, and checks of the actual quadrature nodes on every interval. The check occurs before expensive probes and again on actual P3 centers. This is a conservative numerical resolution policy, not a certified quadrature error bound. All other calculations are retained; four default author replays have exactly unchanged numeric payloads and logs, apart from file-path/source-hash metadata.

The candidate has not yet replaced the live source: the parent must first receive the historical rejection, then integrate only independently approved exact bytes. Review the candidate itself, not any live project source.

Copy inputs/candidate into a NEW private output directory /mnt/f/tools/math-audit-round9-20260923/software-reviewer2. Its script and three sibling imports/table are complete. Read scripts before executing. Run test_f1.py normally and with -O in that private copy; it writes results next to itself. test_candidate.py is the original regression harness copied beside the NEW candidate, so it tests the candidate, not the rejected copy in the historical zip. Run it normally/-O with --output to fresh files. sensitivity.py also writes beside its copy. Use current CLI defaults for four named cases, plus meaningful R=1 and width-weighted checks. The author run_defaults.py is a provenance record with an external old-output comparison path; do not use it to read outside this packet. Instead compare new outputs with the supplied candidate JSON records, excluding only source_sha256 path/hash metadata.

The first-review zip preserves its frozen inputs and real execution, including original historical source and the first candidate, plus independent checks and the F1 reproducer. Prior verdicts are context, not a substitute for the new review. Do not alter any source project, installed plugin, global configuration or original archive. Save real argv/exit/stdout/stderr, script identities and your final numerical records in the private output directory and identify that directory in your final JSON so the coordinator can archive it.
''')
Inputs=[dict(path=F.relative_to(P).as_posix(),role='frozen-numerical-program-and-evidence') for F in sorted((P/'inputs').rglob('*')) if F.is_file()]
Claims=[
	dict(id='R9-final-bump-resolution',verification='software',statement='Independently inspect and execute the repaired bump support/node validation. Reproduce rejection of 1e-20 and 1e-16 widths normally and under -O, including a partially represented support and a distinct-endpoint interval with collapsed quadrature nodes. Check that defaults preserve individual unit masses and nonzero requested directions, failures use nonzero exit before misleading P3 values, and high quadrature orders/overlapping breaks have honest behavior. Evaluate the numerical guard as a finite resolution policy, not a theorem or arbitrary blanket validation.'),
	dict(id='R9-final-numerical-regression',verification='software',statement='Compare actual current candidate with the rejected predecessor in the supplied archive, then personally run the existing normal/-O regressions against the NEW candidate, four named default CLI cases, and meaningful R=1 and width-weighted checks. Check true block-integral projection, zero normals, weighted normalization, unweighted pairings, direct tangency checks, finite-step positivity guards and default data/log preservation. Verify imported modules really are the supplied siblings and record hashes. Do not treat the author replay manifest or prior partial approvals as new execution.'),
	dict(id='R9-final-software-scope',verification='numerical',statement='Check current cutoff/quadrature/finite-difference sensitivity, the small INF relative error and double-precision cancellation remain represented honestly. Check P2b was not wrongly diagnosed as the old block-average defect and P3 remains a fixed-width finite comparison with the negative half-interface acceleration. No infinite spectral-tail bound, root-enumeration certificate, stationary certificate, Hessian definiteness, box feasibility, eta-limit identity or global optimum may be inferred. Preserve both historical rejection and successful scoped behaviors, and report remaining actionable defects without inventing a universal numerical guarantee.')]
Spec=dict(kind='mathematics',author_ids=['01a06f46-dd03-7c83-9267-32048412c359','01a0cbe7-3a93-7ec3-94d5-1481aa88a92d'],inputs=Inputs,claims=Claims)
for N,Vv in [('software-isolated-review2-spec.json',Spec),('software-isolated-review2-packet.json',V.create_packet(P,Spec)),('software-review2-root.json',dict(project=str(P),relative_project=str(P.relative_to(R))))]:(O/N).write_text(json.dumps(Vv,ensure_ascii=False,indent=2)+'\n')
print('Software second-review packet ready',len(Inputs),'inputs',flush=True)
